Repository henpemaz/Rain-Meadow, pull requests merged in 2024-09, with the labels that each got.

#273 Banhammer
  Menu/Objects/SimplerSymbolButton.cs
  Online/RPCs.cs
  Online/Resource/Lobby.cs
  Online/UserModeration/Banhammer.cs
  Story/OnlineUIComponents/SpectatorOverlay.cs
Labels: engine

#277 preserve non-gameplay remix settings
  Story/StoryMenu.cs
Labels: story

#275 sync gravity cycle
  Game/RainMeadow.GameHooks.cs
  Online/Resource/OnlineResource.State.cs
  Online/Resource/WorldSession.RainCycle.cs
  Online/Resource/WorldSession.cs
Labels: story, meadows

#270 Story: fix start cutscenes
  Game/RainMeadow.GameHooks.cs
  Story/StoryHooks.cs
Labels: story

#278 simpler one-off RPCs with InvokeOnceRPC
  Arena/ArenaHooks.cs
  Game/RainMeadow.GameplayHooks.cs
  Game/RainMeadow.PlayerHooks.cs
  Online/OnlinePlayer.cs
  Story/StoryHooks.cs
Labels: engine

#286 don't grab objects for remote players
  Game/RainMeadow.PlayerHooks.cs
Labels: engine

#282 cleanup scav bomb code, sync singularity bombs
  Game/RainMeadow.GameplayHooks.cs
  Online/Entity/OnlinePhysicalObject.cs
  Online/State/OnlineState.cs
  Online/State/PhysicalObjectEntityState.cs
  Online/State/RealizedWeaponState.cs
Labels: story

#279 sync visited echoes
  GameModes/StoryGameMode.cs
  Online/RPCs.cs
  Story/StoryHooks.cs
  Story/StoryLobbyData.cs
Labels: story
