Repository henpemaz/Rain-Meadow, pull requests merged in 2025-09, with the labels that each got.

#1046 Pointing tweaks and fixes
  Game/RainMeadow.PlayerHooks.cs
  OnlineUIComponents/Pointing.cs
Labels: story, arena

#992 Stop PlacedObjects from being loaded before the RoomSession is available.
  Game/RainMeadow.GameHooks.cs
  Game/RainMeadow.LoadingHooks.cs
  Game/RainMeadow.ObjectHooks.cs
  Online/Resource/RoomSession.cs
Labels: engine

#994 add spec to input pausing
  Meadow/Creatures/CreatureController.cs
  OnlineUIComponents/InputOverride.cs
Labels: engine

#1025 Timeline fix
  Game/RainMeadow.LoadingHooks.cs
  GameModes/MeadowGameMode.cs
  GameModes/OnlineGameMode.cs
  GameModes/StoryGameMode.cs
  Online/Entity/OnlineSeedPod.cs
Labels: story, meadows

#1027 More aggressive autohide for the emote grid
  Meadow/MeadowEmoteHud.cs
Labels: ui

#1057 Un-dupe arena's "change player view" button
  Menu/Components/ButtonDisplayer.cs
Labels: bug, ui
